# Generated by Django 3.2.5 on 2022-08-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=100, null=True, verbose_name='Apellido/s')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electronico')),
                ('provincia', models.CharField(max_length=100, null=True, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=100, null=True, verbose_name='Ciudad')),
                ('dni', models.BigIntegerField(null=True, verbose_name='DNI')),
                ('cuil', models.BigIntegerField(null=True, verbose_name='Cuil')),
                ('usuario', models.CharField(max_length=100, null=True, verbose_name='Nombre usuario')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Dirección')),
                ('fecha', models.DateField()),
                ('usuario_activo', models.BooleanField(default=True)),
                ('restablecer', models.BooleanField(default=False)),
                ('es_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
