# Generated by Django 3.2.5 on 2022-08-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='es_admin',
            field=models.BooleanField(default=True),
        ),
    ]
