# Generated by Django 3.2.5 on 2022-08-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='restablecer_password',
            new_name='restablecer',
        ),
    ]
