# Generated by Django 3.2.5 on 2022-08-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_restablecer_password_myuser_restablecer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='restablecer',
            field=models.BooleanField(),
        ),
    ]
