# Generated by Django 3.2.5 on 2022-08-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_myuser_restablecer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='restablecer',
            field=models.CharField(max_length=200),
        ),
    ]
