# Generated by Django 3.2.5 on 2022-08-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_myuser_restablecer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='restablecer',
            field=models.BooleanField(default=False),
        ),
    ]
