# Generated by Django 3.2.5 on 2022-08-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=models.TextField(max_length=1300, null=True),
        ),
    ]
