# Generated by Django 3.2.5 on 2022-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagenes_2',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagenes_3',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagenes_4',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='introduccion_imagen_2',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='introduccion_imagen_3',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='introduccion_imagen_4',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='texto_imagen_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='texto_imagen_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='texto_imagen_4',
            field=models.TextField(null=True),
        ),
    ]
