# Generated by Django 3.2.5 on 2022-08-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20220811_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=models.TextField(null=True),
        ),
    ]
