# Generated by Django 3.2.5 on 2022-08-16 03:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticias_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='texto',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
