# Generated by Django 3.2.5 on 2022-08-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticias_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='introduccion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
