# Generated by Django 3.2.5 on 2022-08-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_noticias_introduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='introduccion',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
