# Generated by Django 3.2.5 on 2022-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticias_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='noticias/'),
        ),
    ]
