# Generated by Django 3.2.5 on 2022-08-29 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('duracion', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(null=True, upload_to='cursos/')),
                ('imagen', models.ImageField(null=True, upload_to='cursos/')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='cursos/')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
    ]
