# Generated by Django 3.2.5 on 2022-08-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoria_curso',
        ),
    ]
