# Generated by Django 3.2.5 on 2022-08-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
        migrations.AddField(
            model_name='alumno',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='creditos'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True, verbose_name='emails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
