# Generated by Django 3.2.5 on 2022-08-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20220818_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
