# Generated by Django 3.2.5 on 2022-08-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_alter_alumno_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
