# Generated by Django 3.2.5 on 2022-08-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_alter_alumno_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='password',
        ),
    ]
