# Generated by Django 3.2.5 on 2022-08-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0007_rename_date_of_birth_myuser_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='es_admin',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='is_active',
            new_name='usuario_activo',
        ),
    ]
