# Generated by Django 3.2.5 on 2022-08-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0008_auto_20220818_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='apellido',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellido/s'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='dni',
            field=models.IntegerField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre/s'),
        ),
    ]
