# Generated by Django 3.2.5 on 2022-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0009_auto_20220818_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='contra',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
