# Generated by Django 3.2.5 on 2022-08-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0012_myuser_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cuil',
            field=models.BigIntegerField(max_length=20, null=True, verbose_name='Cuil'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dni',
            field=models.BigIntegerField(max_length=20, null=True, verbose_name='DNI'),
        ),
    ]
